apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlship
  template:
    metadata:
      labels:
        app: mlship
    spec:
      containers:
        - name: mlship
          image: mlship:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-volume
              mountPath: /model
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-pvc
